### ISSUE TITLE
Redundant promises recursion

### ISSUE THREAD

**Issue by jakwuh** [ftdebugger/di.js#8]
I noticed some places in code, which I think could be optimized into for..in statements:

[nextFactory](https://github.com/ftdebugger/di.js/blob/master/index.js#L665)
[nextLoader](https://github.com/ftdebugger/di.js/blob/master/index.js#L408)
and more

Do we really need to wait for promise to resolve to check if there is a non-falsy result? I think the better way for performance is to make an agreement with all loaders: once question "do you have a dependency with such a `name`" is asked, a loader should answer it in synchronous way, but still could resolve the dependency asynchronously.

Does it make sense?

**Comment by jakwuh** [comment]
It worth mention, that I've already tried to refactor `nextLoader` into for...in statement locally, and the code has passed all tests.

**Comment by ftdebugger** [comment]
There are no real promises in process. If all factories or loaders are synchronous, the process will be synchronous. No one promise will be produced. 

`nextLoader` can be rewrited to `for`, but not `nextFactory`.

**Comment by jakwuh** [comment]
@ftdebugger my comment is more about recursion (as you mention - not necessarily promises recursion).
for..in works faster then functions invocation.
Also, `nextFactory` can be refactored too (just tested it locally):

``` javascript
for (let i = 0; i < factories.length; ++i) {
    let instance = factories[i](definition, dependencies);
    if (instance) {
        return instance;
    }
}
```

**Comment by ftdebugger** [comment]
Yes, but it not solve situation, when factory return promise, that resolve in null.

**Comment by jakwuh** [comment]
Of course, and my initial question was: is that the needed case?
I can't imagine any solid reason for resolver to answer with promise and then resolve it with null. From the point of resolver it is something like: `you want to know if I can resolve this dependency? Ok, that's not a problem. Take this promise and wait, I will discover if I have such a dependency`.
In the past (remember AMD with require.js) it was OK for resolver to act this way. But now perfomance is `the new sexy`. So in case above resolver could bundle the list of its dependencies and then answer always synchronously.

**Comment by jakwuh** [comment]
I will measure an impact of this feature (allow resolvers to answer asynchronously) and then will let you know. 
Please, don't close this thread.

**Comment by ftdebugger** [comment]
👍 PR welcome

**Comment by jakwuh** [comment]
Seems there is no perf issues. Closing issue.
